name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rustup
      run: rustup update stable && rustup default stable
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: poppler-utils
        version: 1.0
    - uses: Swatinem/rust-cache@v2.7.3
    - name: Check Format
      run: cargo fmt --verbose --check
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --all-targets --verbose
    - name: Run tests
      run: cargo test --verbose
